server:
  port: 8000

spring:
  security:
    user:
      name: open
      password: open
  application:
    name: @artifactId@
    
eureka:
  instance:
    hostname: open-eureka
    prefer-ip-address: true
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaulZone: http://open:open@${eureka.instance.hostname}:${server.port}/eureka/
      
      